# Week 4 Homework 3 (Due on Monday, Feb. 24 at 11:59PM)
Split the dataset used in this week's class into training_data (80%) and test_data (20%). Build kNN model with k=1, 15, 50 on the training set. Calculate the prediction accuracy on the test set. 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Load the data set
url = "https://raw.githubusercontent.com/empathy87/The-Elements-of-Statistical-Learning-Python-Notebooks/master/data/mixture.txt"
data = pd.read_csv(url, sep=',')
data.head()

x1        x2  y
0  2.526093  0.321050  0
1  0.366954  0.031462  0
2  0.768219  0.717486  0
3  0.693436  0.777194  0
4 -0.019837  0.867254  0

In [3]:
data.shape

(200, 3)

In [4]:
# Missing values?
pd.isnull(data).sum()

x1    0
x2    0
y     0
dtype: int64

In [5]:
# Split the data set into training set (80%) and test set (20%), 
from sklearn.model_selection import train_test_split
training_data, test_data = train_test_split(data, test_size=0.2)

In [6]:
training_data.shape

(160, 3)

In [7]:
test_data.shape

(40, 3)

## kNN model, k = 1

In [8]:
# Train a k-nearest-neighbor model on the training data, k = 1
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(training_data[["x1", "x2"]], training_data[["y"]])

/Users/elqtrct/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [9]:
# Use the model to make predictions on examples in test data.
predictions = knn.predict(test_data[["x1", "x2"]])
predictions

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0])

#### Accuracy Score

In [10]:
# Calculate the prediction accuracy on the test set
from sklearn.metrics import accuracy_score
accuracy_score(test_data['y'], predictions )

0.675

## kNN model, k = 15

In [11]:
# Train a k-nearest-neighbor model on the training data, k = 15
knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(training_data[["x1", "x2"]], training_data[["y"]])

/Users/elqtrct/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                     weights='uniform')

In [12]:
# Use the model to make predictions on examples in test data.
predictions = knn.predict(test_data[["x1", "x2"]])
predictions

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0])

#### Accuracy Score

In [13]:
# Calculate the prediction accuracy on the test set
from sklearn.metrics import accuracy_score
accuracy_score(test_data['y'], predictions )

0.825

## kNN model, k = 50

In [14]:
# Train a k-nearest-neighbor model on the training data, k = 50
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(training_data[["x1", "x2"]], training_data[["y"]])

/Users/elqtrct/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=50, p=2,
                     weights='uniform')

In [15]:
# Use the model to make predictions on examples in test data.
predictions = knn.predict(test_data[["x1", "x2"]])
predictions

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0])

#### Accuracy Score

In [16]:
# Calculate the prediction accuracy on the test set
from sklearn.metrics import accuracy_score
accuracy_score(test_data['y'], predictions )

0.7